### ISSUE TITLE
Aggiungere Bottom Navigation

### ISSUE THREAD

**Issue by tasca-a** [UnimibSoftEngCourse2022/progetto-birra-1-beer2beer#1]
Dobbiamo implemetare la Bottom Navigation come nel mockup.
Credo che questo potrebbe esserci utile: [Bottom Navigation - Material Design](https://material.io/components/bottom-navigation/android)

![image](https://user-images.githubusercontent.com/81073987/149008995-7e6d378a-3c92-414b-8331-a8b71396d736.png)

La Bottom Navigation deve restare invisibile durante le schermate di Welcome e di GetStarted.

**Comment by sh44** [comment]
Una soluzione potrebbe essere di fare due activity separate. La prima che gestisce il primo login (welcome + richiesta nome) per i nuovi utenti, la seconda invece che contiene i vari fragment del bottom nav menu

**Comment by GiacoLenzo2109** [comment]
Ok, ho appena fatto la bottom van view con navigazione nella stessa activity.
L' idea di fare su due activity separate potrebbe avere senso per poter separare i concetti ma non so se ha senso in quanto lavoriamo con un viewmodel condiviso.

**Comment by GiacoLenzo2109** [comment]
Inoltre nel caso volessimo fare l' item centrale (lampadina) come nel mockup (leggermente più grande) dobbiamo "separarlo" dalla bottom nav e fare un fab.

Altre soluzioni?

**Comment by sh44** [comment]
Si potrebbe ancorare il fab alla bottom nav, qualcosa di [questo tipo](https://stackoverflow.com/questions/50145541/new-bottom-layout-from-google). Un'altro riferimento potrebbe essere anche [questo](https://www.geeksforgeeks.org/how-to-add-a-floating-action-button-to-bottom-navigation-bar-in-android/).

Mi pare abbastanza semplice da implementare, avevi dubbi rispetto all'avere un fab?

**Comment by sh44** [comment]
In alternativa si potrebbe pensare di agire graficamente avendo un bottom nav menu alto come il bottone centrale e ridurre le icone di quelli laterali, ma non so quanto convenga. Se c'è un'alternativa migliore penso sia da preferire

**Comment by GiacoLenzo2109** [comment]
Si, con l' utilizzo del fab bisogna fare un item centrale nella bottom nav view che è vuoto e ci ancoriamo il fab.

**Comment by tasca-a** [comment]
> Ok, ho appena fatto la bottom van view con navigazione nella stessa activity. L' idea di fare su due activity separate potrebbe avere senso per poter separare i concetti ma non so se ha senso in quanto lavoriamo con un viewmodel condiviso.

Concordo.
Stiamo lavorando con un'architettura a singola activity, quindi direi di mantenerla tale anche per ridurre la complessità.
Per gestire il fatto che la BottomNavigation deve restare invisibile durante la schermata di benvenuto e quella di inserimento del nome basta renderla visibile/invisibile programmaticamente in base alla destination in cui ci troviamo ([qui c'è tutto ciò di cui abbiamo bisogno](https://developer.android.com/guide/navigation/navigation-ui#listen_for_navigation_events))
Per far sì che le schermate di welcome e di benvenuto vengano skippate semplicemente facciamo un check delle sharedpreferences e, se il nome è già stato inserito, navighiamo direttamente nella homepage.
