### ISSUE TITLE
Aggiungere il mockup della schermata Impostazioni

### ISSUE THREAD

**Issue by tasca-a** [UnimibSoftEngCourse2022/progetto-birra-1-beer2beer#4]
Nel mockup manca la schermata delle impostazioni.
Probabilmente manca perché non sappiamo ancora bene cosa metterci, ma un'idea sarebbe quella di dare all'utente la possibilità di cancellare i propri dati per far ripartire l'applicazione "come nuova".

**Comment by sh44** [comment]
Dunque ci sarebbe un button per l'eliminazione dei dati e basta?
L'utente potrebbe decidere di cambiare il nome inserito all'inizio?

**Comment by tasca-a** [comment]
Si, possiamo fare un tasto per l'eliminazione dei dati (reset totale) e uno per cambiare il proprio nome.
Direi che per ora possono bastare.

**Comment by sh44** [comment]
Pagina settings aggiunta al mockup.
