### ISSUE TITLE
Aggiunta Splash screen

### ISSUE THREAD

**Issue by Bonfanti-Samuele** [UnimibSoftEngCourse2022/progetto-birra-1-beer2beer#6]

**Comment by sh44** [comment]
Lo splash screen conterrà il logo dell'applicazione?
Eventualmetne va bene quello del mockup o c'erano altre idee?

**Comment by tasca-a** [comment]
> Lo splash screen conterrà il logo dell'applicazione? Eventualmetne va bene quello del mockup o c'erano altre idee?

Si a entrambe le domande per me.
Però prioritizzerei altre core features in questo momento

**Comment by tasca-a** [comment]
@sh44 riusciresti a fornirmi l'icona della nostra applicazione? Mi servirebbe in formato vettoriale :smile:

**Comment by sh44** [comment]
[BrewDay!_logo.svg.zip](https://github.com/UnimibSoftEngCourse2022/progetto-birra-1-beer2beer/files/7904721/BrewDay._logo.svg.zip)

Certo! Mando il file zippato perchè non supporta file .svg ':D
